### ISSUE TITLE
non-wildcard and wildcard router conflict, why?

### ISSUE THREAD

**Issue by 1046102779** [julienschmidt/httprouter#210] opened 2017-07-31 03:37 UTC
![image](https://user-images.githubusercontent.com/20457624/28761881-87cadf80-75e4-11e7-97cf-39c0ebb7ce8f.png)

**Comment by GuihToledo** [comment] 2017-08-18 18:32
I have the same problem, looking the issues history, other peoples pointed this problem years ago, but have never fixed =/.

**Comment by shinriyo** [comment] 2017-09-18 06:43
Me too.
It is inconvenience.

```
func (controller *ShopsController) Setup() {
        controller.Router.POST("/shops", controller.createShop)
        controller.Router.GET("/shops", controller.listShops)
        //controller.Router.GET("/shops/new", controller.newShop) // conflict!!
        controller.Router.GET("/shops/:shop_id", controller.getShop)
        controller.Router.GET("/shops/:shop_id/edit", controller.editShop)
        controller.Router.PUT("/shops/:shop_id", controller.updateShop)
        controller.Router.DELETE("/shops/:shop_id", controller.deleteShop)
}
```

I also use `Group` but conflict!
```
func (controller *ShopsController) Setup() {
        v1 := controller.Router.Group("/shops")
        {
                v1.POST("", controller.createShop)
                v1.GET("", controller.listShops)
                //v1.GET("/new", controller.newShop) // conflict!!
                v1.GET("/:shop_id", controller.getShop)
                v1.GET("/:shop_id/edit", controller.editShop)
                v1.PUT("/:shop_id", controller.updateShop)
                v1.DELETE("/:shop_id", controller.deleteShop)
        }
}
```

**Comment by shinriyo** [comment] 2017-09-18 06:44
I guess `/:hoge` and `/somthing` are conflicts.

**Comment by sciencefyll** [comment] 2017-10-07 14:32
@julienschmidt please take a look.

This repo isn't dead right?

**Comment by jomendoz** [comment] 2017-10-16 20:52
#175

**Comment by martijnotto** [comment] 2017-10-27 11:49
I have an even stranger conflict:

router.GET("/:room/:screen/up", handler)
router.GET("/socket", handler)

I cannot fathom how this could be a conflict, since /socket would not match the pattern of the first route, since it misses part of the path.

**Comment by andersfylling** [comment] 2017-10-27 11:50
check out chi if you are in need of a better repo. (sorry for saying better, but wildcards work as expected)

**Comment by go101** [comment] 2018-07-15 15:20
You can try TinyRouter: https://github.com/go101/tinyrouter

**Comment by julienschmidt** [comment] 2019-09-25 23:49
Duplicate of #183

**Closed by julienschmidt** 2019-09-25 23:49 UTC
