### ISSUE TITLE
Static routing collision.

### ISSUE THREAD

**Issue by husio** [julienschmidt/httprouter#91] opened 2015-07-17 14:52 UTC
Hi,

I have two endpoints - one of them return entity for given group in specified version, while the other returns the latest entity for given group. Routing should look like this:  
```go
router.GET("/:group_id/latest", redirectToLatest)
router.GET("/:group_id/:version_id", entityDetails)
```
Right now it's no possible. Definition order does not matter.

```
panic: path segment 'latest' conflicts with existing wildcard ':version_id' in path '/:group_id/latest' [recovered]   panic: path segment 'latest' conflicts with existing wildcard ':version_id' in path '/:group_id/latest'
```
I could check in `entityDetails` if `version_id` is `latest` and that's what I do right now, but it would be way nicer to allow to define static route, even if dynamic one already cover the same case.

**Comment by julienschmidt** [comment] 2015-07-17 14:54
Duplicate of #73

**Closed by julienschmidt** 2015-07-17 14:54 UTC
